### ISSUE TITLE
我感觉空白页面还是太过单调了，或许添加个什么api？一言？或者古诗词？

### ISSUE THREAD

**Issue by xiamuguizhi** [flyhaozi/Blank-New-Tab-Page---White-Smoke#13]
这是我下载您开源代码，在本地修改后启用的效果，如下图：

![image](https://user-images.githubusercontent.com/19650297/223035365-b53c0634-e095-476d-95b0-44bf62891706.png)

调用的API：

`<img src="https://v1.jinrishici.com/all.svg?font-size=30&spacing=4">`

**Comment by yuhaofe** [comment]
不好意思，这个项目追求的主要还是极简化，不会增加类似的功能
不过项目代码是MIT协议的，你可以自由修改发布 :)
