### ISSUE TITLE
Support the use in incognito/inprivate mode

### ISSUE THREAD

**Issue by Kees1958** [flyhaozi/Blank-New-Tab-Page---White-Smoke#4]
Hi,

I like your empty new tab page. The smoke option makes it easy on the eyes, thanks. 

Would it also be possible to use your extension inprivate (Edge's incognito mode)?

Bruce Blank Tab can also be used incognito/inprivate. Blank New Tab Page from Jarek Foksa also runs incognito and offers a darker background color. Maybe you could have a look at it and offer a slightly darker grey smoke background when incognito/inprivate.

Thanks

/K

**Comment by yuhaofe** [comment]
This is a good idea, I'll look into it.

**Comment by yuhaofe** [comment]
The new version has been submitted to chrome web store and edge addons store, it may take a few days to review.

**Comment by Kees1958** [comment]
Thanks I starred your extension, great job

**Comment by Kees1958** [comment]
@flyhaozi  Could you make the incognito lighter shade of grey (change it from #222222 to #999999)?

**Comment by yuhaofe** [comment]
I make the light mode color #999999 and dark mode color #222222 in incognito mode.
