### ISSUE TITLE
背景闪烁

### ISSUE THREAD

**Issue by JmyFilm** [flyhaozi/Blank-New-Tab-Page---White-Smoke#6]
当Edge浏览器为黑色主题时，新建标签页时会从闪烁白色背景。
可能背景默认是白色的，JS判断浏览器主题耗时造成的闪烁。

**Comment by yuhaofe** [comment]
感谢反馈，问题已复现，的确是JS设置主题的时机过晚，正在尝试修复中~

**Comment by yuhaofe** [comment]
尝试进行了修复，已经基本上不会出现闪烁了，更改将会随着下个版本发布。
